; in FUJIAPPLE.S
		.WORD 	relocate000+1,relocate001+1,relocate002+1,relocate003+1,relocate004+1,relocate005+1,relocate006+1,relocate007+1,relocate008,relocate009
		.WORD 	relocate010,relocate011,relocate012,relocate013,relocate014,relocate015,relocate016,relocate017,relocate018,relocate019
		.WORD   relocate020,relocate021,relocate022;,relocate023,relocate024,relocate025,relocate026,relocate027,relocate028,relocate029
